language: swift
osx_image: xcode10.2
xcode_workspace: KinSDK.xcworkspace
xcode_scheme: KinSDKTests
xcode_sdk: iphonesimulator12.2

env:
- TEST_MATRIX=build
- TEST_MATRIX=test

script:
  - |
    if [ $TEST_MATRIX == "build" ]; then 
      xcodebuild -workspace KinSDK.xcworkspace -scheme KinSDKSampleApp -sdk iphonesimulator12.2 -configuration "Debug"
    fi
  - |
    if [ $TEST_MATRIX == "test" ]; then
      # inject integration environment params for testing from env variable by string replacing content of a template file  
      sed -e  "s@INTEG_TESTS_NETWORK_URL@$INTEG_TESTS_NETWORK_URL@" -e "s@INTEG_TESTS_NETWORK_PASSPHRASE@$INTEG_TESTS_NETWORK_PASSPHRASE@" -e "s@INTEG_TESTS_NETWORK_FRIENDBOT@$INTEG_TESTS_NETWORK_FRIENDBOT@" scripts/IntegEnvironmentTemplate.swift > KinSDKTests/IntegEnvironment.swift
      xcodebuild test -workspace KinSDK.xcworkspace -scheme KinSDKTestsHost -destination 'platform=iOS Simulator,name=iPhone X'
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)